# mongoid 5.x
#
production:
  clients:
    default:
     # The standard MongoDB connection URI allows for easy
     # replica set connection setup.
     # Use environment variables or a config file to keep your
     # credentials safe e.g. <%= ENV['MONGOLAB_URI'] %>.
     uri: 'mongodb://heroku_x0tf84bt:5rbsfc0uadvs91l7snhlr957kf@ds019628.mlab.com:19628/heroku_x0tf84bt'

     options:
       # The default timeout is 5, which is the time in seconds
       # for a connection to time out.
       # We recommend 15 because it allows for plenty of time
       # in most operating environments.
       connect_timeout: 15


development:
  clients:
    default:
      uri: mongodb://localhost:27017/smichki


test:
  sessions:
    default:
      database: grape_bootstrap_test
      hosts:
        - localhost:27017


